export const moods: { [key: string]: string } = {
    Angry: '😡',
    Sad: '😞',
    Neutral: '😐',
    Happy: '😊',
    Excited: '🤩',
};

export const reasons = [
    'Celebrations',
    'Adventure',
    'Rejection',
    'Surprises',
    'Daily Chores',
    'Health',
    'Work',
    'Negative Feedback',
    'Children',
    'Heartbreak',
    'Hobbies',
    'Loneliness',
    'New Purchases',
    'Rudeness',
    'School',
    'Family',
    'Friends',
    'Love',
    'Girlfriend',
    'Boyfriend',
    'Wife',
    'Husband',
    'Parents',
    'Health',
    'Money',
    'Pets',
    'Politics',
];
