export const moods: { [key: string]: string } = {
    Angry: '😡',
    Sad: '😞',
    Neutral: '😐',
    Happy: '😊',
    Excited: '🤩',
};

export const reasons = [
    'Celebrations',
    'Adventure',
    'Rejection',
    'Surprises',
    'Health',
    'Work',
    'Children',
    'Heartbreak',
    'Hobbies',
    'Loneliness',
    'Rudeness',
    'School',
    'Family',
    'Friends',
    'Love',
    'Girlfriend',
    'Boyfriend',
    'Wife',
    'Husband',
    'Parents',
    'Money',
    'Pets',
    'Politics',
    'Religion',
    'Weather',
    'Sports',
    'Traffic',
    'Music',
    'Movies',
    'Books',
];
